export enum RolesIDs {
    INDEXATION_ADMINISTRATEUER = 'INDEXATION_ADMINISTRATEUER',
    INDEXATION_INJECTEUR = 'INDEXATION_INJECTEUR',
    INDEXATION_INDEXEUR = 'INDEXATION_INDEXEUR',
    INDEXATION_CONTROLEUR = 'INDEXATION_CONTROLEUR',
    INDEXATION_ATTRIBUTEUR_LOTS = 'INDEXATION_ATTRIBUTEUR_LOTS',
    INDEXATION_GESTIONNAIRE_DONNEES = 'INDEXATION_GESTIONNAIRE_DONNEES',
}